[package]
name = "derive_utils"
version = "0.0.1"
edition = "2024"
authors = ["markhenry.liwag@gmail.com"]

[dependencies]
change-case = "0.2.0"
deluxe = "0.5.0"
proc-macro2 = "1.0.94"
quote = "1.0.40"
regex = "1.11.1"
syn = "2.0.100"