[package]
name = "postgresql_derive"
version = "0.0.1"
edition = "2024"
authors = ["markhenry.liwag@gmail.com"]

[dependencies]
deluxe = "0.5.0"
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = "2.0.100"

derive_utils = { path = "../derive_utils" }

[lib]
proc-macro = true